# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Saavi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Saavi
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
  pod 'Lightbox'
  pod 'KDCalendar'
  pod 'Stripe'
    pod 'GooglePlaces'
    pod 'iOSDropDown'
  target 'SaaviTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SaaviUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
